apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:DohelMoto/DohelMoto-GitOps.git
      targetRevision: staging
      ref: values
    - repoURL: git@github.com:DohelMoto/DohelMoto.git
      targetRevision: staging
      path: my-helm
      helm:
        valueFiles:
          - $values/environments/staging/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
