apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dohelmoto-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:DohelMoto/DohelMoto-GitOps.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:DohelMoto/DohelMoto.git
      targetRevision: main
      path: my-helm
      helm:
        valueFiles:
          - $values/environments/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
